spring:
  application:
    name: user-management
  datasource:
    url: jdbc:postgresql://localhost:5432/db_user_management
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9090
  servlet:
    contextPath: /user-management

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
